# Generated by Django 5.1.1 on 2024-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0003_alter_techique_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='technique/madia/%Y/%m/%d'),
        ),
    ]
